"""
autonomous_agent.py — Orchestrates autonomous repository-level code reviews and architectural documentation.
"""

import os
import logging
from typing import Any, Dict

logger = logging.getLogger(__name__)


class AutonomousRepositoryAgent:
    """Runs automated end-to-end repository code scans and documents architecture."""

    def __init__(self, analyzer: Any) -> None:
        self.analyzer = analyzer

    def run_autonomous_scan(self) -> Dict[str, Any]:
        """Perform a complete repository review and write a README_ai_scan.md summary."""
        # 1. Generate Architecture Report
        logger.info("Generating architecture report autonomously...")
        arch_report = self.analyzer.generate_architecture_report()

        # 2. Find major modules to review
        logger.info("Identifying key files for review...")
        most_connected = self.analyzer._kg.get_most_connected(top_k=3)
        reviewed_files = []
        reviews = []

        for item in most_connected:
            file_path = item[0]
            # Verify file exists
            full_path = os.path.join(self.analyzer.repo_path, file_path)
            if os.path.exists(full_path) and os.path.isfile(full_path):
                logger.info("Reviewing code file: %s", file_path)
                review_txt = self.analyzer.run_code_review(file_path)
                reviewed_files.append(file_path)
                reviews.append(f"### Code Review for `{file_path}`:\n\n{review_txt}\n")

        # 3. Compile Master Documentation
        master_doc = f"""# 🤖 Autonomous AI Repository Scan Report

This report was autonomously generated by the Antigravity Codebase Agent.

## 🏗️ Architecture & Structural Assessment

{arch_report}

## 🔍 Key Module Reviews

{"\n---\n\n".join(reviews) if reviews else "No code reviews executed."}
"""

        # 4. Write to file
        output_file = os.path.join(self.analyzer.repo_path, "README_ai_scan.md")
        try:
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(master_doc)
            logger.info("Saved autonomous report to: %s", output_file)
            status = "Success"
        except Exception as exc:
            logger.error("Failed to write scan report: %s", exc)
            status = f"Error: {exc}"

        return {
            "status": status,
            "reviewed_files": reviewed_files,
            "report_path": output_file,
        }
